### ISSUE TITLE
Sample site reloading every couple of frames.

### ISSUE THREAD

**Issue by jindalpratik** [Shivansh-Khunger/Vihaan#3]
The sample site seems to reload every couple pf seconds causing it to disconnect from server.

**Comment by Shivansh-Khunger** [comment]
I would suggest writing our own code in react for front-end working on it 👍. Meanwhile I would suggest @jindalpratik to take a look at the backend code for any unexpected connection lose at its part.

**Comment by jindalpratik** [comment]
> I would suggest writing our own code in react for front-end working on it 👍. Meanwhile I would suggest @jindalpratik to take a look at the backend code for any unexpected connection lose at its part.

Yeah rather than fixing my quickly put together site it would probably be better to create a new one. As for the backend As far as I can tell there is not really anything that would cause a site reload. Closing this issue as not relevant anymore.
