### ISSUE TITLE
Significant Delay in Video Feed

### ISSUE THREAD

**Issue by Shivansh-Khunger** [Shivansh-Khunger/Vihaan#6]
In this video you can clearly see that there is an **unacceptable delay** in the live webcam feed and the received frames from the python backend.

I believe there are 2 reasons for this -:

- Async nature of `useState` in React. @Pranit223 could you check my implementation pushing the code in branch within 10-12 minutes.
- Maybe the backend is also not that fast either. @jindalpratik could you confirm this?

The combination of these two is making the video feed **laggy & delayed**. I will continue looking for better alternatives on how to make the performance better 👍.

https://github.com/Shivansh-Khunger/Vihaan/assets/110467229/bc622264-55a2-4615-aca2-15866ede53d8

[Solution Given By Chat-GPT](https://chat.openai.com/share/0c36f40c-c33c-486d-a3a3-f19eb5879b03)

**Comment by jindalpratik** [comment]
Backend currently processes the feed pretty much real time so really shouldn't be an issue on the backend side, you can try commenting out the debug code for saving the images in backend and see if that helps @Shivansh-Khunger .

**Comment by jindalpratik** [comment]
The currently processes the feed pretty much real time so really shouldn't be an issue on the backend side, you can try commenting out the debug code for saving the images in backend and see if that helps @Shivansh-Khunger .

Edit: We should also probably merge the react site into main for now and work on the bugs as we go, can also encode the returned image in base64 and serve in via a different websocket connection if you would prefer that.

**Comment by Shivansh-Khunger** [comment]
I have implemented the `base64` also as the `blob` implementation was creating a lot of compatibility issues.

**Comment by jindalpratik** [comment]
> I have implemented the `base64` also as the `blob` implementation was creating a lot of compatibility issues.

Should I implement it in the backend too?

**Comment by Shivansh-Khunger** [comment]
@jindalpratik  I meant backend only
